FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat  # ✅ Ajout pour corriger le warning SWC

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3001
CMD ["npm", "start"]
