version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-db
      - PORT=4000
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/orders-db
      - PORT=3003
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27020:27017" # Si tu veux te connecter en local, laisse 27020:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=products-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Remets "5433:5432" si nécessaire
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  mongo-data:
  postgres-data:
